### ISSUE TITLE
using https return error

### ISSUE THREAD

**Issue by rvwv** [anton-iermolenko/Azure-IIS-Hosted-RavenDb#4]
Hello Anton,

any idea why i get this error on studio when i connect via https or use OAuth authentication mode?
i looking to secure ravendb studio you have any suggestions ?

than

Message: The remote server returned an error: NotFound.
Server Uri: https://domain.cloudapp.net:8080/build/version?noCache=-2072117194

more  info about error :

-- Error Information --
System.Net.WebException: The remote server returned an error: NotFound. ---> System.Net.WebException: The remote server returned an error: NotFound.
   at System.Net.Browser.ClientHttpWebRequest.InternalEndGetResponse(IAsyncResult asyncResult)
   at System.Net.Browser.ClientHttpWebRequest.<>c__DisplayClass5.<EndGetResponse>b__4(Object sendState)
   at System.Net.Browser.AsyncHelper.<>c__DisplayClass4.<BeginOnUI>b__1(Object sendState)
   --- End of inner exception stack trace ---
   at System.Net.Browser.AsyncHelper.BeginOnUI(SendOrPostCallback beginMethod, Object state)
   at System.Net.Browser.ClientHttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Func`2.Invoke(T arg)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endMethod, TaskCompletionSource`1 tcs)

Inner StackTrace: 
   at Raven.Studio.Infrastructure.InvocationExtensions.Catch(Task parent, Action`1 action)
   at Raven.Studio.Infrastructure.InvocationExtensions.Catch(Task parent)
   at Raven.Studio.Infrastructure.Model.TimerTicked()
   at Raven.Studio.Infrastructure.View.<InvokeTimerTicked>b__7(Model model)
   at Raven.Studio.Infrastructure.View.InvokeOnModel(Object ctx, Action`1 action)
   at Raven.Studio.Infrastructure.View.InvokeTimerTicked(Object ctx)
   at Raven.Studio.Infrastructure.View.DispatcherTimerOnTick(Object sender, EventArgs eventArgs)
   at MS.Internal.CoreInvokeHandler.InvokeEventHandler(Int32 typeIndex, Delegate handlerDelegate, Object sender, Object args)
   at MS.Internal.JoltHelper.FireEvent(IntPtr unmanagedObj, IntPtr unmanagedObjArgs, Int32 argsTypeIndex, Int32 actualArgsTypeIndex, String eventName)

thanks

**Comment by anton-iermolenko** [comment]
Didn't dig into that direction yet. You should check out and ask on RavenDb groups: https://groups.google.com/forum/#!forum/ravendb
